X= int(input("What is the amount of part 1?"))
Y= int(input("What is the amount of part 2?"))
Z= int(input("What is the amount of part 3?"))
Parttotal=(X+Y+Z)
Totalweight= int(input("What is the total weight of the drug?"))
Ratio=(Parttotal/Totalweight)
PartX=(X*Totalweight)/(Parttotal)
PartY=(Y*Totalweight)/(Parttotal)
PartZ=(Z*Totalweight)/(Parttotal)
print ("The weight of part 1 is",round (PartX, 1),"mg")
print ("The weight of part 2 is",round (PartY, 1),"mg")
print ("The weight of part 3 is",round (PartZ, 1),"mg")