while True:
    print("1. Daily Dose")
    print("2. BSA")
    print("3. Clarks")
    print("4. Pillcount")
    print("5. 3 Part Weight Ratio")
    print("6. Flow Rate")
    print("7. Solution with Ratio")
    print("8. W/V Solutions")
    choice=input()
    if choice=="1":
        LBS=int(input("What is the patient's weight?" ))
        KG=(LBS/2.2)
        MG=int(input("What is the tablet strength?" ))
        SIG= int(input("How many times a day is the dose?" ))
        DOSE=(MG*SIG)
        DAILY=(DOSE/KG)
        print ( round (DAILY, 1))
    if choice=="2":
        LBS=int(input("What is the patient's weight in lbs?" ))
        ADULTDOSE=int(input("What is the adult dose in mg?" ))
        KG=(LBS/2.2)
        BSA=((4*KG+7)/(KG+90))
        CHILDDOSE=(BSA/1.7*ADULTDOSE)
        print ("The patient's weight in KG is",round (KG, 1),"kg")
        print ("The body surface area of the patient is",round(BSA, 1))
        print ("The child dose is",round (CHILDDOSE, 1),"mg")
    if choice=="3":
        AD=int(input("What is the adult dose?" ))
        CW=int(input("What is the child weight in lbs?" ))
        CD= (AD*(CW/150))
        print ("The child dose is" , round (CD, 0 ), "mg")
    if choice=="4":
        Concentration = 400/5
        Volume = int(input("What is the volume needed?" ))
        Dose = int(input("What is the  pill strength?" ))
        Pillcount = ((Concentration * Volume) / Dose)
        print(Pillcount)
    if choice=="5":
        X= int(input("What is the amount of part 1?"))
        Y= int(input("What is the amount of part 2?"))
        Z= int(input("What is the amount of part 3?"))
        Parttotal=(X+Y+Z)
        Totalweight= int(input("What is the total weight of the drug?"))
        Ratio=(Parttotal/Totalweight)
        PartX=(X*Totalweight)/(Parttotal)
        PartY=(Y*Totalweight)/(Parttotal)
        PartZ=(Z*Totalweight)/(Parttotal)
        print ("The weight of part 1 is",round (PartX, 1),"mg")
        print ("The weight of part 2 is",round (PartY, 1),"mg")
        print ("The weight of part 3 is",round (PartZ, 1),"mg")
    if choice=="6":
        Volume=int(input("What is the total number of mL given?"))
        Time=int(input("What is the total minutes the dose is given?"))
        Drops=int(input("What is the number of drops per mL?"))
        DropFactor=(Drops*Volume)
        FlowRate= (DropFactor/Time)
        print ("The number of drops per minute is", round (FlowRate,0))
    if choice=="7":
        Ratio =eval(input("What is the ratio of the solution?"))
        RP= (Ratio*100)
        Volume=int(input("What is the current volume?"))
        Percent=float(input("What is the current percent?"))
        Solution=(Volume*Percent)/(RP)
        print (Solution)
    if choice=="8":
        Percent=float(input("What is the percent w/v?"))
        ML= int(input("What is the amount of solution in mL?"))
        Solution=(Percent*ML)
        Answer=(Solution/100)
        print (Answer)
